In [104]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [105]:
df=pd.read_csv(r'signal_metrics.csv')

In [106]:
df.head()

,Timestamp,Locality,Latitude,Longitude,Signal Strength (dBm),Signal Quality (%),Data Throughput (Mbps),Latency (ms),Network Type,BB60C Measurement (dBm),srsRAN Measurement (dBm),BladeRFxA9 Measurement (dBm)
0,2023-05-05 12:50:40.000000,Anisabad,25.599109,85.137355,-84.274113,0.0,1.863890,129.122914,3G,0.000000,0.000000,0.000000
1,2023-05-05 12:53:47.210173,Fraser Road,25.433286,85.070053,-97.653121,0.0,5.132296,54.883606,4G,-95.810791,-105.452359,-99.920892
2,2023-05-05 12:56:54.420346,Boring Canal Road,25.498809,85.211371,-87.046134,0.0,1.176985,119.598286,LTE,-91.593861,-95.419482,-87.714070
3,2023-05-05 13:00:01.630519,Danapur,25.735138,85.208400,-94.143159,0.0,68.596932,46.598387,5G,-90.642773,-101.895905,-96.570698
4,2023-05-05 13:03:08.840692,Phulwari Sharif,25.538556,85.159860,-94.564765,0.0,38.292038,30.342828,5G,-90.489100,-103.318304,-95.102467

In [107]:
df.columns

Index(['Timestamp', 'Locality', 'Latitude', 'Longitude',
       'Signal Strength (dBm)', 'Signal Quality (%)', 'Data Throughput (Mbps)',
       'Latency (ms)', 'Network Type', 'BB60C Measurement (dBm)',
       'srsRAN Measurement (dBm)', 'BladeRFxA9 Measurement (dBm)'],
      dtype='str')

In [108]:
cols = df.columns

In [ ]:
#df[cols].dtypes

Timestamp                           str
Locality                            str
Latitude                        float64
Longitude                       float64
Signal Strength (dBm)           float64
Signal Quality (%)              float64
Data Throughput (Mbps)          float64
Latency (ms)                    float64
Network Type                        str
BB60C Measurement (dBm)         float64
srsRAN Measurement (dBm)        float64
BladeRFxA9 Measurement (dBm)    float64
dtype: object

In [ ]:
#memory usage of each column in bytes
#df[cols].memory_usage(deep=True)

Index                               132
Timestamp                       1262175
Locality                        1016916
Latitude                         134632
Longitude                        134632
Signal Strength (dBm)            134632
Signal Quality (%)               134632
Data Throughput (Mbps)           134632
Latency (ms)                     134632
Network Type                     862503
BB60C Measurement (dBm)          134632
srsRAN Measurement (dBm)         134632
BladeRFxA9 Measurement (dBm)     134632
dtype: int64

In [ ]:
#df[cols].memory_usage(deep=True).sum()

np.int64(4353414)

In [ ]:
(df
 [cols]
 .select_dtypes('str'));

                        Timestamp           Locality Network Type
0      2023-05-05 12:50:40.000000           Anisabad           3G
1      2023-05-05 12:53:47.210173        Fraser Road           4G
2      2023-05-05 12:56:54.420346  Boring Canal Road          LTE
3      2023-05-05 13:00:01.630519            Danapur           5G
4      2023-05-05 13:03:08.840692    Phulwari Sharif           5G
...                           ...                ...          ...
16824  2023-06-10 23:44:23.950552        Pataliputra           4G
16825  2023-06-10 23:47:31.160725  Boring Canal Road          LTE
16826  2023-06-10 23:50:38.370898        Boring Road           5G
16827  2023-06-10 23:53:45.581071        Boring Road           3G
16828  2023-06-10 23:56:52.791244     Rajendra Nagar          LTE

[16829 rows x 3 columns]

In [ ]:
df.Locality.value_counts();

Locality
Fraser Road          897
Gandhi Maidan        885
Phulwari Sharif      880
Exhibition Road      876
Kidwaipuri           873
Boring Road          851
Pataliputra          850
Gardanibagh          846
Boring Canal Road    841
Kumhrar              840
Kankarbagh           834
Ashok Rajpath        832
Bailey Road          831
Anisabad             830
Bankipore            825
Rajendra Nagar       817
Patliputra Colony    811
Danapur              809
S.K. Puri            802
Anandpuri            799
Name: count, dtype: int64

In [114]:
df.Locality.describe()

count           16829
unique             20
top       Fraser Road
freq              897
Name: Locality, dtype: object

In [ ]:
(df[cols]
 .groupby('Locality')
 ['Network Type']
 .value_counts())

SyntaxError: invalid syntax (3596022308.py, line 4)

In [119]:
#heat map of sites and measurements
#finding long and limits of map
minLong = (df[cols]
 .Latitude
 .idxmin())
maxLong = (df[cols]
 .Latitude 
 .idxmax())
minLat = (df[cols]
 .Longitude
 .idxmin())
maxLat = (df[cols]
    .Longitude
    .idxmax())